### ISSUE TITLE
relative path is wrong when fileName contains a directory

### ISSUE THREAD

**Issue by ArloL** [laynezh/vite-plugin-lib-assets#14]
Thank you so much for creating this plugin.

I create two different output directories for the different two formats es and cjs. I got the idea from 
https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html

This is the config I am using right now:

```
…
export default defineConfig({
  plugins: [
    …
    libAssetsPlugin({
      limit: 1024 * 8,
      extensions: ['.jpg', '.png', '.otf', '.ttf', '.woff'],
    }),
  ],
  build: {
    lib: {
      entry: path.resolve(__dirname, 'src/index.js'),
      formats: ['es', 'cjs'],
      fileName: (format) => {
        if (format === 'es') {
          return 'mjs/index.js';
        }
        return `${format}/index.js`;
      },
    },
    …
  },
});
```

Sadly the asset path is kept at `./assets` in the index.js files. I now added a build step that copies the assets into the mjs and cjs directories. Is there any chance that you might be able to change the  imports to `../assets` instead?

**Comment by coder-layne** [comment]
Thank you for your feedback. The plugin will adjust the extracted resource's address according to the importer's output path from v0.4.2.

**Comment by ArloL** [comment]
I just tried 0.4.3 and it works. Thank you very much. For me this issue can be closed ☺️
