### ISSUE TITLE
The plugin cannot generate the correct relative path when preserveModules is enabled.

### ISSUE THREAD

**Issue by Nathan7139** [laynezh/vite-plugin-lib-assets#30]
There is a `preserveModules` setting within `rollupOptions` that preserves the source code's folder structure, making sure the `dist` directory reflects it. In this case, `vite-plugin-lib-assets` will produce incorrect paths such as `./assets`.

For why someone need `preserveModules`: https://github.com/vitejs/vite/discussions/2447#discussioncomment-6768114

To resolve this issue, I change the "resolveId" behavior:
```ts
import { createFilter } from 'vite'
import libAssetsPluginF from '@laynezh/vite-plugin-lib-assets'
import fs from 'fs'
import * as path from 'path'

const libAssetsPluginOptions = {
  // include: 'src/assets/{img,icon}/**/*',
  include: 'src/assets/img/**/*',
  exclude: '**/*.{css,scss,vue}',
}
const libAssetsPlugin = libAssetsPluginF({
  include: libAssetsPluginOptions.include,
  exclude: libAssetsPluginOptions.exclude,
  // limit: 1024 * 1000,
  name: '[name].[ext]',
  outputPath: (url, resourcePath) => {
    const outputPath = resourcePath.replace(/\/[^/]+$/, '')
      .replace(__dirname, './')
    return outputPath
  }
})
const assetsContentMap = new Map()
const filter = createFilter(
  libAssetsPluginOptions.include,
  libAssetsPluginOptions.exclude
)
libAssetsPlugin.resolveId = function(source, importer = '') {
  const importerDir = importer.endsWith(path.sep) ? importer : path.dirname(importer);
  const id = path.resolve(importerDir, source);
  if (!filter(id) || id.includes('*')) return null
    
  // EmitFile to have it show up in the dist.
  if (!assetsContentMap.get(id)) {
    const pureId = id.split("?")[0]
    if (!fs.existsSync(pureId)) {
      console.warn(`[vite-plugin-lib-assets]: file not found ${id}`);
      return null
    } else {
      const filename = source.replace(/^.+assets/, 'src/assets')
      const fullname = source.replace(/^.+assets/, path.join(__dirname, 'src/assets'))
      const content = fs.readFileSync(pureId);
      assetsContentMap.set(id, content);
      this.emitFile({
        type: 'asset',
        fileName: filename,
        name: fullname,
        source: content,
      })
    }
  }

  // Return result
  const assetPath = path.relative(
    path.dirname(importer),
    id,
  )
  return {
    id: `./${assetPath}`,
    external: "relative",
  }
}

export default libAssetsPlugin
```
If the path contains a wildcard, the plugin will issue a warning about not being able to find the file and return null. However, this warning doesn't lead to any bugs; it's simply a false alarm.

**Comment by coder-layne** [comment]
Thank you for your feedback. I'm not very familiar with the `preserveModules` setting. I need to research its impact on `resolveId` and fix this issue asap.

**Comment by coder-layne** [comment]
@Nathan7139 In the latest code, when the file doesn't exist, `resolveId` returns `null` and defers to other `resolveId` functions. You can upgrade to the latest version to check if it resolves your issue.

**Comment by fanlion** [comment]
> Thank you for your feedback. I'm not very familiar with the `preserveModules` setting. I need to research its impact on `resolveId` and fix this issue asap.

一般用这个属性的，是想用vite按源码目录结构，把ts，vue、less文件转成js、css文件，同时保留目录结构。这样就可以把任意的代码做成npm包，可以把一个项目拆成monorepo，而不用刻意去设计目录结构，和限制使用方式。

**Comment by coder-layne** [comment]
> > Thank you for your feedback. I'm not very familiar with the `preserveModules` setting. I need to research its impact on `resolveId` and fix this issue asap.
> 
> 一般用这个属性的，是想用vite按源码目录结构，把ts，vue、less文件转成js、css文件，同时保留目录结构。这样就可以把任意的代码做成npm包，可以把一个项目拆成monorepo，而不用刻意去设计目录结构，和限制使用方式。
So when I configured this option, what will happen to the parameters of the `resolveId`?

**Comment by Nathan7139** [comment]
> @Nathan7139 In the latest code, when the file doesn't exist, `resolveId` returns `null` and defers to other `resolveId` functions. You can upgrade to the latest version to check if it resolves your issue.

Sorry for confusing, wildcard problem and `preserveModules` problem are different issue. Wildcard problem just give a warning and didn't break anything, it's fine.
The main issue is `preserveModules` problem. If I have this folder structure:
```
- my proj
  - dist
  - src
    - assets
    - utils
      - testUtils.ts
    - main.ts
    - App.vue
    - vite.config.ts
```
and `preserveModules` options in my vite. Build result will be:
```
- my proj
  - dist
    - src
      - assets
        - a.png
      - utils
        - testUtils.es.js
      - main.es.js
      - App.vue.es.js
  - src
    - assets
      - a.png 
    - utils
      - testUtils.ts
    - main.ts
    - App.vue
    - vite.config.ts
```
But this plugin always give path like `dist/assets/a.png` not `dist/src/assets/a.png`. [My code](https://github.com/laynezh/vite-plugin-lib-assets/issues/30#issue-1937336655) fix this problem, by it only fit my project, so it just a reference for you.

**Comment by coder-layne** [comment]
@Nathan7139 I understand your point, in such cases, you can use the [`outputPath`](https://github.com/laynezh/vite-plugin-lib-assets#outputpath) option to customize the output directory for different assets.

**Comment by Nathan7139** [comment]
> @Nathan7139 I understand your point, in such cases, you can use the [`outputPath`](https://github.com/laynezh/vite-plugin-lib-assets#outputpath) option to customize the output directory for different assets.我理解你的觀點，在這種情況下，你可以使用 `outputPath` 選項來自訂不同資產的輸出目錄。 For your folder structure, you can config `outputPath` like this: 對於您的資料夾結構，您可以像這樣配置 `outputPath` ：
> 
> ```
> outputPath(_, resourcePath) {
>   if (resourcePath.includes('src/assets'))
>     return 'src/assets'
>   return 'assets'
> },
> ```

But what about if there are folders in `assets`? Like:
```
- my proj/
  - src/
    - assets/
      - setting/
        - b.jpg
      - a.png 
```
For plugin result, both a.png and b.jpg will in the same folder. Like:
```
- my proj/
  - dist/
    - src/
      - assets/
        - setting/
          - b.jpg
        - a.png
```

**Comment by coder-layne** [comment]
> > @Nathan7139 I understand your point, in such cases, you can use the [`outputPath`](https://github.com/laynezh/vite-plugin-lib-assets#outputpath) option to customize the output directory for different assets.我理解你的觀點，在這種情況下，你可以使用 `outputPath` 選項來自訂不同資產的輸出目錄。 For your folder structure, you can config `outputPath` like this: 對於您的資料夾結構，您可以像這樣配置 `outputPath` ：
> > ```
> > outputPath(_, resourcePath) {
> >   if (resourcePath.includes('src/assets'))
> >     return 'src/assets'
> >   return 'assets'
> > },
> > ```
> 
> But what about if there are folders in `assets`? Like:
> 
> ```
> - my proj/
>   - src/
>     - assets/
>       - setting/
>         - b.jpg
>       - a.png 
> ```
> 
> For plugin result, both a.png and b.jpg will in the same folder. Like:
> 
> ```
> - my proj/
>   - dist/
>     - src/
>       - assets/
>         - setting/
>           - b.jpg
>         - a.png
> ```

In this scenario, you can configure it like this:
```
outputPath(url, resourcePath) {
  if (['.jpg', '.png'].includes(extname(url)))
    return dirname(resourcePath).replace(__dirname, '')
  return 'assets'
},
```
Where `extname` and `dirname` come from the built-in `path`.
