### ISSUE TITLE
tsup kills import.meta.url in cjs build

### ISSUE THREAD

**Issue by Ambroos** [laynezh/vite-plugin-lib-assets#31]
Hi!

In my project setup I was temporarily using an older module system that ended up using CommonJS imports in my Vite config. The CommonJS build of this plugin seems to be broken since v0.5.4, because of the addition of this line in compiler.ts:

```typescript
const _require = createRequire(import.meta.url)
```

`import.meta` gets replaced by an empty object, which makes the `url` undefined, and `createRequire` throws.

You may be able to fix this with some simple tsup config: https://tsup.egoist.dev/#inject-cjs-and-esm-shims

I worked around it by fixing my TypeScript config so I would not use the cjs import, but I think it's still worth fixing.

**Comment by coder-layne** [comment]
Thank you for your feedback, I'll fixed this problem soon.

**Comment by Ambroos** [comment]
Looks good now, thanks for taking this on so fast!

**Comment by coder-layne** [comment]
> Looks good now, thanks for taking this on so fast!

It's benifit from the accurate information you provide.
