### ISSUE TITLE
The plugin cannot generate the correct umd.js

### ISSUE THREAD

**Issue by MuD11** [laynezh/vite-plugin-lib-assets#33]
format : umd

1、without publicUrl, it is not works.
`(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined'
    ? (module.exports = factory(require('vue'), require('./assets/317a6ac8d841c94f.png')))
    : typeof define === 'function' && define.amd
    ? define(['vue', './assets/317a6ac8d841c94f.png'], factory)
    : ((global = typeof globalThis !== 'undefined' ? globalThis : global || self),
      (global.index = global.index || {}),
      (global.index.vue = factory(global.vue, global._imports_0)))
})(this, function (vue, _imports_0) {`

the png neet to be defined inrequireJS (define(['vue', './assets/317a6ac8d841c94f.png'], factory))，but we need is img：src

2、use publicUrl, it works.
`!(function (e, t) {
  'object' == typeof exports && 'undefined' != typeof module
    ? (module.exports = t(require('vue')))
    : 'function' == typeof define && define.amd
    ? define(['vue'], t)
    : ((e = 'undefined' != typeof globalThis ? globalThis : e || self).index = t(e.vue))
})(this, function (e) {
  'use strict'
  const t = e.createElementVNode('img', { src: 'xxxx/xxx.png' }, null, -1),`

i hope this issue can be fixed,thanks.

**Comment by MuD11** [comment]
I thought about it, maybe this is the feature

**Comment by coder-layne** [comment]
> publicUrl

@MuD11 You're right, it's a feature. If you have a dedicated service for hosting assets, you can specify the `publicUrl`. Otherwise, assets within the package will be handled by the package user.
