### ISSUE TITLE
[Bug] Plugin halts the build process in library mode

### ISSUE THREAD

**Issue by voknelis** [laynezh/vite-plugin-lib-assets#48]
## Description
In some cases, this plugin appears to trigger a freeze in Vite's build process when referencing assets using the '../' path. As a result, the build process becomes unresponsive at a certain stage, preventing its completion. It's worth noting that despite this freeze, all the build outputs are successfully generated and available within the 'dist' (or 'lib') folder.

## Context (Environment)
- Vite v3.2.5 or higher;
- Vue v3.x;
- @laynezh/vite-plugin-lib-assets v0.5.8

## Steps to Reproduce
1. Open the [reproduction repo sandbox](https://codesandbox.io/p/devbox/vite-vue3-vite-plugin-lib-assets-issue-demo-zhp47c?file=%2Fsrc%2Fcomponents%2FHelloWorld.vue%3A5%2C35);
2. Execute `yarn build` command. Notice, that the built process halts after processing several modules;
3. Navigate to the `HelloWorld.vue` component out comment the following line:
`<img src="../assets/logo.png">`;
4. Run the `yarn build` command again. This time, observe that the project successfully builds in library mode.

--
Let me know, if you need any additional information.

**Comment by coder-layne** [comment]
@voknelis Thank you for your feedback and patiently providing a lot of valuable clues.

**Comment by coder-layne** [comment]
@voknelis It's fixed in v0.5.9, you can view the results online [here](https://codesandbox.io/p/devbox/vite-vue3-vite-plugin-lib-assets-issue-demo-forked-h73hdf).

**Comment by voknelis** [comment]
Thanks a lot, it works now!
Didn't expect it to get fixed so fast tho :D

**Comment by coder-layne** [comment]
@voknelis It's benifit from the accurate information you provide.
