### ISSUE TITLE
Emitted files overwriting warning from Rollup

### ISSUE THREAD

**Issue by mcmimik** [laynezh/vite-plugin-lib-assets#50]
### Issue
I'm encountering a lot of console messages from Rollup like this one:

> The emitted file "assets/5576df4aa8e2a231.svg" overwrites a previously emitted file of the same name.

This warning suggests that the same asset file is being emitted multiple times with the same name, leading to potential overwrites.

### Expected Behavior
Ideally, the plugin should handle asset emissions in a way that prevents duplication. Each unique asset should only be emitted once, or if re-emitted, should be handled in a way that doesn't trigger Rollup's overwrite warning.

### Possible Solution
A potential solution could be implementing a caching mechanism or a list of already emitted files within the plugin. This would prevent `emitFile` from processing and emitting the same file more than once during the build process.

## Steps to Reproduce

1. Include multiple components in the project that reference the same SVG assets.
2. Run the build process using `npm run build`.
3. Observe the Rollup messages in the console indicating that the same file is being emitted multiple times.

Here is the StackBlitz example with the Rollup messages in terminal: https://stackblitz.com/edit/vue3-vite-lib-assets-overwrite?file=src%2Fassets%2Fflags%2Fflag-icon.css

## Additional Context

**Version: 0.5.9**

The issue appears not only when the same SVG file (or a CSS file with SVG links) is used multiple times in different components, but also when Rollup processes the same file with different query parameters. This situation is common in Vue projects, where a file might be imported several times with different queries, leading to the same file being emitted more than once. For instance:

- `../../assets/styles/flag-icon.css`
- `../../assets/styles/flag-icon.css?vue&type=style&index=1&src=true&lang.css`

These different ways of importing the same file are treated separately by the plugin, causing Rollup to warn about overwriting files. A solution that recognizes and handles these similar imports as one could potentially solve this issue.

Btw, is it normal that the build is called twice? You can see this in the StackBlitz example above.

## Suggested Implementation

I have no idea what is the good pattern for that kind of situations, but maybe implementing a caching system or a set to keep track of already emitted files could resolve this issue. For example, maintaining a record of emitted file names and checking this before calling `emitFile` could prevent unnecessary duplicate emissions.

---

Btw, thank you for developing and maintaining such a useful plugin!

**Comment by coder-layne** [comment]
@mcmimik Thank you for patiently providing so much information to help me find the source of the problem.

As you said, it is a good way to avoid `rollup` warnings by recording files that have already been emitted through cache. The built-in asset plugin in `Vite` will also undergo a [cache check](https://github.com/vitejs/vite/blob/v5.0.2/packages/vite/src/node/plugins/asset.ts#L362-L366) before [emitFile](https://github.com/vitejs/vite/blob/v5.0.2/packages/vite/src/node/plugins/asset.ts#L398).

The issue you mentioned about "build twice" is actually "build once and generate twice". In the Vite, if you do not pass in formats, [it will default to using two formats](https://github.com/vitejs/vite/blob/v5.0.2/packages/vite/src/node/build.ts#L837-L839), `['es', 'cjs']` or `['es', 'umd']`. If you have two formats, you will [get two outputs](https://github.com/vitejs/vite/blob/v5.0.2/packages/vite/src/node/build.ts#L856), and then you need to [generate twice](https://github.com/vitejs/vite/blob/v5.0.2/packages/vite/src/node/build.ts#L698-L700).

**Comment by coder-layne** [comment]
@mcmimik It's fixed in v0.5.10, you can view the results online [here](https://stackblitz.com/edit/vue3-vite-lib-assets-overwrite-sho5h9?file=package.json).

**Comment by mcmimik** [comment]
Hi, I've just checked out v0.5.10 and everything is working smoothly now. Thanks a lot for the quick fix and for keeping the plugin up to date!

**Comment by Pong420** [comment]
This issue happen again with version `1.1.0`. 
It can be reproduced with the example provided with the latest version
https://stackblitz.com/edit/vue3-vite-lib-assets-overwrite-sho5h9?file=package.json
