### ISSUE TITLE
build.cssCodeSplit option causes wrong file resolution 

### ISSUE THREAD

**Issue by mspae** [laynezh/vite-plugin-lib-assets#60]
I have a project with `build.cssCodeSplit: true` (https://vitejs.dev/config/build-options#build-csscodesplit)

In this project there is a CSS file which has a `background-image: url("xxx.jpg");`

The file `xxx.jpg` is correctly bundled into the output directory as a file. However, the outputted CSS includes the base64 encoded image, not the path to the file on disk.

Setting the `build.cssCodeSplit` property to false causes the issue to disappear. (But obviously I would prefer not to ;) )

Cheers!

**Comment by coder-layne** [comment]
@mspae Thanks for your feedback, I'll try to reproduce the issue and fix it soon.

**Comment by coder-layne** [comment]
@mspae I find the problem, it's because [this piece of code](https://github.com/laynezh/vite-plugin-lib-assets/blob/42fd0201d984a261e6b58843224129b12d83d8c4/src/index.ts#L156-L167) repeatedly consumes the iterator, and except for the initial iteration, subsequent ones fail to produce the expected results.

**Comment by coder-layne** [comment]
@mspae I just released v0.5.15, hoping it resolves the issue you encountered.

**Comment by mspae** [comment]
@coder-layne Wow! Thanks for the quick fix! The new release fixes the issue. The base64-encoded image is no longer in the source code. :champagne: 

I don't know if this is fixable easily enough. It's purely aesthetic at this point: The build stats read as though the image was included.

**Comment by coder-layne** [comment]
@mspae Sorry, I didn't quite understand. Is the "build stats" here the output built into Vite or the content produced by a certain plugin? How should I configure it to see the "stats" you mentioned?

**Comment by mspae** [comment]
The "normal" vite build output. Like this one (just an example):

![](https://blog.logrocket.com/wp-content/uploads/2020/06/vitebundling.png)

So the image file is 500kb, the css file is 10kb. With the new version of the plugin the output does not contain the 500kb but reports as 600kb in the build output. So I'm guessing the part that is counting the size happens before the base64 image is replaced with the image file path.

**Comment by coder-layne** [comment]
@mspae You're right. Assets in CSS are replaced after Vite processes them, making it challenging to optimize this issue directly. I'll invest some time in research, but don't set high expectations.

**Comment by mspae** [comment]
:+1:  No worries. As I said this is purely aesthetic. Maybe we could add a caveat on the README so people aren't confused.

**Comment by coder-layne** [comment]
@mspae I'll explore its feasibility first. If it turns out to be impossible, I'll include a caveat in the README.

**Comment by sonikdesign** [comment]
I'm fixing a new Vite project and I've (almost) solved the problem thanks to this package. After doing the build, there is a mismatch only for CSS. 

I'm in the same case, with cssCodeSplit on true.
Images are ok, but CSS files are not renamed like in the build js file. Here the CSS files have a name with random string at the end. On `dist` folder the CSS files have original names. As soon as I can I'll open a specific issue with more details.

**Comment by coder-layne** [comment]
@sonikdesign It would be excellent if you could open a specific issue, preferably with a reproducible configuration.

**Comment by coder-layne** [comment]
@mspae I just fixed the output bundle size issue and released v0.5.16.

**Comment by mspae** [comment]
Thanks @coder-layne ! I'll close this issue.
