### ISSUE TITLE
Usage with SSR?

### ISSUE THREAD

**Issue by segevfiner** [laynezh/vite-plugin-lib-assets#63]
If I build a library that is to be imported as external in SSR and it imports any assets, it will fail to import as node doesn't know how to import such asset files. How should one configure something like this to work? Building a library with external assets that can still work in Node that is? Trying to build using Vite's `--ssr` flag to produce a separate build doesn't help, I guess this plugin doesn't look into that...

**Comment by coder-layne** [comment]
@segevfiner In the past, I have not encountered scenarios used under SSR. Since there are people like you with such needs, I intend to explore the feasibility of this approach.

**Comment by segevfiner** [comment]
You can try this: https://github.com/segevfiner/vite-lib-assets-ssr-mwe

Basically I want to have an SSR/node build of `packages/foo` that can be used in a backend as for SSR or just for plain code that needs to be used in Node but must be defined inside that package that is built by Vite and has web parts.

Run:
1. `pnpm i`
2. `pnpm build`
3. `pnpm start`

And you will see node complain about being unable to import the externalized svg (Which might be why Vite opted for keeping assets inline in lib mode, or maybe due to the UMD build for use without a bundler?)

I also tried building the lib in SSR mode, which is not really intended for lib mode as far as I can tell, e.g. `build.lib.format` causes it to also build CJS in this project rather than only ESM which it does by default, it doesn't rename the entry so you get `index.js` instead of `foo.js`, so there might need to be a separate issue against Vite to make this actually well supported or do this in a different way that is more supported.

But it still externalizes assets in SSR mode which leads to the same error. So my guess would be to disable this plugin in an SSR build? And utilize exports to direct to the right build:
```json
{
  "exports": {
    "types": "./dist/foo.d.ts",
    "node": "./dist-ssr/index.js",
    "import": "./dist/foo.js",
    "require": "./dist/foo.cjs"
  },
}
```

Bundlers and CJS/ESM is so much fun! 🙄

**Comment by coder-layne** [comment]
@segevfiner I understand what you mean. You can try the [publicUrl](https://github.com/laynezh/vite-plugin-lib-assets#publicurl) configuration option of the plugin. I think that when building the SSR version, the assets should be replaced with the online addresses.

**Comment by segevfiner** [comment]
This can be difficult to use as I need it only for the Node.js build, and the URL might vary as this is in a library that can be consumed by projects with varying deployment URLs.

**Comment by coder-layne** [comment]
@segevfiner How about using different [entry points](https://nodejs.org/docs/latest/api/packages.html#package-entry-points) for the node part and the SSR part?

**Comment by segevfiner** [comment]
Sadly due to technical limitations of some libraries we use, we have code we need in node that does import Vue components which import assets.

**Comment by coder-layne** [comment]
@segevfiner Based on my limited understanding of the SSR process, the source code undergoes transpilation and then is rendered into static HTML by Node. During the transfer, assets are processed into corresponding addresses. However, your description outlines another scenario, and I'm not sure how assets would be handled in this case. Do you have any thoughts on this?
