### ISSUE TITLE
Usage with monorepo

### ISSUE THREAD

**Issue by dwojno** [laynezh/vite-plugin-lib-assets#67]
Hi,
I've been trying to use this plugin with nx monorepo and found a problem with resolving `outDir` from vite config
I've created a branch with a fix but not able to push it to your repo :) 

```ts
const { build, resolve, root } = config
...
outDir = root ? path.join(root, build.outDir) : build.outDir
```

**Comment by coder-layne** [comment]
@dwojno Thank you for your contribution. Please fork this repository, fix the issue in your fork, after then submit a pull request to this repository, and I'll merge it after some necessary review.
