### ISSUE TITLE
Warning when enabling Sourcemaps

### ISSUE THREAD

**Issue by marcelobotega** [laynezh/vite-plugin-lib-assets#68]
Hi, 

when enabling source maps (`build.lib.sourcemaps`) on the config file, vite is showing the following message:

```
(vite-plugin-lib-assets plugin) Sourcemap is likely to be incorrect: a plugin (vite-plugin-lib-assets) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
```

Tested on the playground and the message also shows there. 
Is it possible to generate the sourcemaps ?

**Comment by coder-layne** [comment]
@marcelobotega Thanks for your feedback, I'll confirm the issue and fix it soon.

**Comment by coder-layne** [comment]
@marcelobotega I just fixed the issue and released v0.5.18.

**Comment by marcelobotega** [comment]
As mentioned on the other issue, the fix work.

**Comment by AriPerkkio** [comment]
Why is this plugin transforming files in the first place? The `transform` hook could simply return `undefined`.

**Comment by coder-layne** [comment]
@AriPerkkio Thanks for your reminder, I wasn't aware that this could be done in this way
