### ISSUE TITLE
`?inline` query imports are not supported

### ISSUE THREAD

**Issue by AriPerkkio** [laynezh/vite-plugin-lib-assets#74]
When a Javascript file imports CSS with [`?inline` query](https://vitejs.dev/guide/features.html#disabling-css-injection-into-the-page) the assets of the CSS file are externalized, but the inline CSS inside Javascript file is not transformed.

Reproduction: https://stackblitz.com/edit/vite-plugin-lib-assets-repro?file=main.js

### Input:

```ts
// main.js
import styles from './style.css?inline';
```

```css
// style.css
html {
  @font-face {
    font-family: 'My font';
    src: url(/font-asset.woff2) format('woff2');
  }
}
```

### Output:

```sh
vite v5.1.4 building for production...
✓ 2 modules transformed.
dist/assets/57748073fb67cde0.woff2  0.02 kB                  <-- Looks good, asset is externalized
dist/vite-starter.js                0.16 kB │ gzip: 0.16 kB
✓ built in 152ms
```

```js
// dist/vite-starter.js
const f = '@font-face{html{font-family:My font;src:url(data:font/woff2;base64,Q29udGVudCBvZiBmb250IGhlcmU=) format("woff2")}}';
//                                                                  😢  ^^^^^^^^^^^
export {
  f as default
};
```

There's a file extension filter that prevents modifying `.js` files as it's looking for `.css` files only:

https://github.com/laynezh/vite-plugin-lib-assets/blob/0fd8b3c6d067bf17a278680c9f2cbab9e375edbd/src/index.ts#L155-L173

If the `filter` is removed and the base64 inlines are replaced from JS files also, do we need to update source maps too?

**Comment by coder-layne** [comment]
@AriPerkkio Thanks for your feedback, it's necessary to support.
