### ISSUE TITLE
JavaScript heap out of memory after v0.5.22 upgrade

### ISSUE THREAD

**Issue by piotrpalarz** [laynezh/vite-plugin-lib-assets#81]
Hi, we're using your library in build step on GitHub Actions and yesterday it suddenly stopped working and we get an error like this. When I force the version to 0.5.21 it works again. We use the plugin like this:
```
libAssetsPlugin({
    include: /\/fonts\//
})
```

![image](https://github.com/laynezh/vite-plugin-lib-assets/assets/3818431/000b98e7-7946-4079-bce7-3bc44eac30d3)

I would be grateful if you can fix this. This plugin is great, thank you for creating it.

**Comment by coder-layne** [comment]
@piotrpalarz Thank you for your feedback and sorry for broken your project, I'll fix this soon.

**Comment by coder-layne** [comment]
@piotrpalarz I've just reproduced the issue you encountered, and I'll try to fix it.

**Comment by coder-layne** [comment]
@piotrpalarz This issue was caused by the changes made in issue 79. I will roll back these changes in the next version to fix the more severe crash problem mentioned here.
