### ISSUE TITLE
Not working for scss import fonts

### ISSUE THREAD

**Issue by philipp-winterle** [laynezh/vite-plugin-lib-assets#9]
Copied config from your playground and tried with minimal config. 

test.scss
`@import "@fontsource/poppins/index.css";
`

lib entry is
`
entry: {
    mainCss: "./test.scss",      // Entry CSS path
},
`

css font url still inlined as base64

**Comment by coder-layne** [comment]
Try v0.4.0, and the playground has also been updated with the scenarios you mentioned.
