### ISSUE TITLE
dynamic import from node_modules "file not found" 

### ISSUE THREAD

**Issue by SvyatoslavPozhydaev** [laynezh/vite-plugin-lib-assets#90]
If import css file dynamicly like `import("@fortawesome/fontawesome-pro/css/all.min.css");` then get notice 

```
[vite-plugin-lib-assets]: file not found C:\project\src\@fortawesome\fontawesome-pro\css\all.min.css
```

but if set relative path, then it worked

```
import("../node_modules/@fortawesome/fontawesome-pro/css/all.min.css");
```

**Comment by SvyatoslavPozhydaev** [comment]
https://github.com/laynezh/vite-plugin-lib-assets/blob/main/src/index.ts#L241

perhaps to get it you need to use the built-in `resolve` method from the example https://rollupjs.org/plugin-development/#resolveid

```js
const resolution = await this.resolve(source, importer, options);
const id = resolution.id
```

**Comment by coder-layne** [comment]
@SvyatoslavPozhydaev Thank you for your feedback. 

The issue you encountered is similar to #79, and a fix was made based on the built-in `resolve` you mentioned. However, this led to #81, a critical bug, so the change was rolled back.

Since no one else encountered a similar issue afterward, the fix was put on hold. Now that you're facing this problem, I will follow up on it and find a way to fix it.

**Comment by coder-layne** [comment]
@SvyatoslavPozhydaev I just released v0.5.24 under the `next` tag, you can try it to see if it solves your problem.

**Comment by SvyatoslavPozhydaev** [comment]
@coder-layne 

I check this variants

- aliasing import in css  is  worked
```css
@font-face {
  ...
  src: url('@alias/assets/fonts/IBMPlexMono.woff2') format('woff2'),  url('@alias/assets/fonts/IBMPlexMono.woff') format('woff');
  ...
}
```

- import in css is worked

```scss
@import "@fortawesome/fontawesome-pro/css/all.css";
```

- dynamic import in js is worked
```js
import("@fortawesome/fontawesome-pro/css/all.css");
```

- static import in js is worked

```js
import "@fortawesome/fontawesome-pro/css/all.css";
```

**Comment by coder-layne** [comment]
@SvyatoslavPozhydaev Glad the problem is solved, and thank you for the thorough verification.
