### ISSUE TITLE
我用vite开发公共库，在build.lib模式下面，打包生成npm包，在项目中引用包，图片不能正常显示

### ISSUE THREAD

**Issue by yan919** [laynezh/vite-plugin-lib-assets#94]
我使用的是react
<img width="549" alt="image" src="https://github.com/user-attachments/assets/a565d0f2-1d27-4016-95bd-d61a2708980c">
这是es.js文件
<img width="505" alt="image" src="https://github.com/user-attachments/assets/6fb40f51-251d-4069-a8bc-139f9818e8e4">
<img width="795" alt="image" src="https://github.com/user-attachments/assets/8f98223e-a241-45b2-8117-ffeb494afce5">
在项目中引入，src地址有问题
<img width="408" alt="image" src="https://github.com/user-attachments/assets/83138a89-a997-4066-8713-fa72b62a7e10">

**Comment by coder-layne** [comment]
@yan919 能提供一个最小的可复现版本吗

**Comment by coder-layne** [comment]
从es.js的内容来看，插件正常完成了自己的工作，问题可能来自于将包使用在项目中时，把图片当成了javascript中的模块进行了转换，如果是开发模式下，可以试试把包放到optimizeDeps的exclude配置项
